# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modal_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        dialog.resize(952, 783)
        dialog.setMinimumSize(QtCore.QSize(0, 0))
        dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        dialog.setAutoFillBackground(False)
        dialog.setStyleSheet("font-family: Inter;")
        dialog.setSizeGripEnabled(False)
        dialog.setModal(True)
        self.dialog_layout = QtWidgets.QVBoxLayout(dialog)
        self.dialog_layout.setContentsMargins(0, 0, 0, 0)
        self.dialog_layout.setSpacing(0)
        self.dialog_layout.setObjectName("dialog_layout")
        self.background_frame = QtWidgets.QFrame(dialog)
        self.background_frame.setEnabled(True)
        self.background_frame.setStyleSheet("QPushButton {\n"
                                            "    outline: 0;\n"
                                            "}\n"
                                            "\n"
                                            "QComboBox {\n"
                                            "    border-radius: 10px;\n"
                                            "    border: 1px solid #B5B8C7;\n"
                                            "    padding-left: 15px;\n"
                                            "    padding-right: 15px;\n"
                                            "    font-size: 16px;\n"
                                            "    color: #757C9F;\n"
                                            "}\n"
                                            "\n"
                                            "QComboBox:hover {\n"
                                            "    border: 1px solid #0915CC;\n"
                                            "    background: #F2F3F6;\n"
                                            "}\n"
                                            "\n"
                                            "QComboBox::drop-down {\n"
                                            "    border-top-right-radius: 3px;\n"
                                            "    border-bottom-right-radius: 3px;\n"
                                            "}\n"
                                            "\n"
                                            "QComboBox::down-arrow {\n"
                                            "    padding-right: 20px;\n"
                                            "    image: url(:/image/arrow_drop_down.svg);\n"
                                            "}\n"
                                            "\n"
                                            "QComboBox QAbstractItemView\n"
                                            "{\n"
                                            "    background: #F9FAFB;\n"
                                            "    padding-left: 7px;\n"
                                            "    padding-right: 7px;\n"
                                            "    border: 0.5px solid rgba(181, 184, 199, 0.5);\n"
                                            "    border-radius: 8px;\n"
                                            "    outline: 0;\n"
                                            "}\n"
                                            "\n"
                                            "QComboBox QAbstractItemView::item { \n"
                                            "    min-height: 35px;\n"
                                            "    padding-left: 15px;\n"
                                            "    background: #F9FAFB;\n"
                                            "    color: #070808;\n"
                                            "}\n"
                                            "\n"
                                            "QListView::item:selected { \n"
                                            "    color: #0915CC; \n"
                                            "    background-color: #F2F3F6; \n"
                                            "    border-radius: 4px;\n"
                                            "}\n"
                                            "\n"
                                            "QRadioButton {\n"
                                            "    font-size: 14px;\n"
                                            "    color: #070808;\n"
                                            "    outline: 0;\n"
                                            "}\n"
                                            "\n"
                                            "QRadioButton::indicator {\n"
                                            "    width : 20px;\n"
                                            "    height : 20px;\n"
                                            "}\n"
                                            "\n"
                                            "QRadioButton::indicator::checked {\n"
                                            "    image: url(:/image/radio_button_checked.svg);\n"
                                            "}\n"
                                            "\n"
                                            "QLineEdit {\n"
                                            "    border-radius: 10px;\n"
                                            "    border: 1px solid #B5B8C7;\n"
                                            "    padding-left: 15px;\n"
                                            "    padding-right: 15px;\n"
                                            "    font-size: 16px;\n"
                                            "}\n"
                                            "\n"
                                            "QLineEdit:hover {\n"
                                            "    border: 1px solid #0915CC;\n"
                                            "    background-color: #F2F3F6;\n"
                                            "}\n"
                                            "\n"
                                            "QLineEdit:focus {\n"
                                            "    border: 1px solid #0915CC;\n"
                                            "    background-color: #F2F3F6;\n"
                                            "}\n"
                                            "\n"
                                            "QLineEdit[error=true] {\n"
                                            "    border: 1px solid #FF3C2F;\n"
                                            "}\n"
                                            "\n"
                                            "/* QFrame */\n"
                                            "\n"
                                            "#main_frame, #success_frame, #error_frame, #confirm_frame, #asset_main_frame, #asset_type_main_frame, #inventor_item_main_frame, #inventory_preset_main_frame {\n"
                                            "    border-radius: 20px;\n"
                                            "    background-color: rgb(255, 255, 255);\n"
                                            "}\n"
                                            "\n"
                                            "#background_frame {\n"
                                            "    background: rgba(7, 8, 8, 0.2);\n"
                                            "}\n"
                                            "\n"
                                            "/* QPushButton */\n"
                                            "\n"
                                            "#add_user_butt, #success_butt, #confirm_accept_butt, #add_asset_butt, #add_asset_type_butt, #add_inventor_item_butt, #add_inventory_preset_butt {\n"
                                            "    border-radius: 10px;\n"
                                            "    font-size: 15px;\n"
                                            "    color: #FFFFFF;\n"
                                            "    background: #0915CC;\n"
                                            "}\n"
                                            "\n"
                                            "#add_user_butt:hover, #success_butt:hover, #confirm_accept_butt:hover, #add_asset_butt:hover, #add_asset_type_butt:hover, #add_inventor_item_butt:hover, #add_inventory_preset_butt:hover{\n"
                                            "background: rgba(9, 21, 204, 0.8);\n"
                                            "}\n"
                                            "\n"
                                            "#error_butt {\n"
                                            "    border-radius: 10px;\n"
                                            "    font-size: 15px;\n"
                                            "    color: #FFFFFF;\n"
                                            "    background: #FF3C2F;\n"
                                            "}\n"
                                            "\n"
                                            "#error_butt:hover {\n"
                                            "background: rgba(255, 60, 47, 0.8);\n"
                                            "}\n"
                                            "\n"
                                            "#add_user_cancel_butt, #error_cancel_butt, #confirm_cancel_butt, #cancel_asset_butt, #cancel_asset_type_butt, #cancel_inventor_item_butt, #cancel_inventory_preset_butt {\n"
                                            "    border-radius: 10px;\n"
                                            "    border: 1px solid #B5B8C7;\n"
                                            "    font-size: 15px;\n"
                                            "    color: #FFFFFF;\n"
                                            "    color: #757C9F;\n"
                                            "}\n"
                                            "\n"
                                            "#add_user_cancel_butt:hover, #error_cancel_butt:hover, #confirm_cancel_butt:hover, #cancel_asset_butt:hover, #cancel_asset_type_butt:hover, #cancel_inventor_item_butt:hover, #cancel_inventory_preset_butt:hover {\n"
                                            "    color: #0915CC;\n"
                                            "    border: 1px solid #0915CC;\n"
                                            "}\n"
                                            "\n"
                                            "#asset_add_asset_type {\n"
                                            "    background: transparent;\n"
                                            "    font-size: 14px;\n"
                                            "    color: #0915CC;\n"
                                            "    qproperty-icon: url(:/image/round_plus_icon_default.svg);\n"
                                            "    margin-top: 5px;\n"
                                            "}\n"
                                            "\n"
                                            "#asset_add_asset_type:hover, #asset_delete:hover, #asset_type_delete:hover {\n"
                                            "    text-decoration: underline;\n"
                                            "}\n"
                                            "\n"
                                            "#asset_delete, #asset_type_delete {\n"
                                            "    background: transparent;\n"
                                            "    font-size: 14px;\n"
                                            "    color: #FF3C2F;\n"
                                            "    qproperty-icon: url(:/image/delete_acc_icon_hover_red.svg);\n"
                                            "}\n"
                                            "\n"
                                            "/* QLabel */\n"
                                            "\n"
                                            "#header, #success_header, #error_header, #confirm_header, #asset_header, #asset_type_header, #inventory_item_header, #inventory_preset_header{\n"
                                            "    font-size: 28px;\n"
                                            "    color: #070808;\n"
                                            "    margin-bottom: 5px;\n"
                                            "}\n"
                                            "\n"
                                            "#success_header, #error_header, #confirm_header {\n"
                                            "    margin-bottom: 10px;\n"
                                            "    margin-top: 30px;\n"
                                            "}\n"
                                            "\n"
                                            "#add_user_text, #asset_text, #asset_type_text, #asset_type_text_2, #inventory_item_text, #inventory_item_text_2, #inventory_preset_text {\n"
                                            "    font-size: 16px;\n"
                                            "    color: #070808;\n"
                                            "    margin-bottom: 25px;\n"
                                            "}\n"
                                            "\n"
                                            "#error_name, #error_email, #error_pass, #error_pass2, #error_asset_name, #error_asset_type, #error_asset_type_name, #error_dimension, #error_inventory_item_name, #error_inventory_item_dimension, #error_inventory_preset_qty  {\n"
                                            "    margin-top: 5px;\n"
                                            "    font-size: 14px;\n"
                                            "    color: #FF3C2F;\n"
                                            "}\n"
                                            "\n"
                                            "#name_label, #add_user_role_text, #success__text, #error_text, #confirm_text, #asset_name_label, #asset_type_name_label, #sq_feet_label, #length_label, #width_label, #heigth_label, #inventory_item_name_label, #inventory_length_label, #inventory_width_label, #inventory_heigth_label, #inventory_preset_qty_label  {\n"
                                            "    font-size: 16px;\n"
                                            "    color: #7C83A7;\n"
                                            "}\n"
                                            "\n"
                                            "#success__text, #error_text, #confirm_text  {\n"
                                            "    margin-bottom: 30px;\n"
                                            "}\n"
                                            "\n"
                                            "#name_label, #asset_name_label, #asset_name_label, #asset_type_name_label, #sq_feet_label, #inventory_item_name_label, #inventory_preset_qty_label {\n"
                                            "    margin-bottom: 5px;\n"
                                            "}\n"
                                            "\n"
                                            "#email_label, #pass_label, #pass2_label, #asset_type_label, #inventory_preset_list_label {\n"
                                            "    font-size: 16px;\n"
                                            "    color: #7C83A7;\n"
                                            "    margin-bottom: 5px;\n"
                                            "    margin-top: 20px;\n"
                                            "}\n"
                                            "\n"
                                            "#asset_type_text_2, #inventory_item_text_2 {\n"
                                            "    margin-bottom: 0px;\n"
                                            "    margin-top: 25px;\n"
                                            "}\n"
                                            "\n"
                                            "/* Icons */\n"
                                            "\n"
                                            "#success_icon {\n"
                                            "    image: url(:/image/acc_created_pic.svg);\n"
                                            "}\n"
                                            "\n"
                                            "#error_icon {\n"
                                            "    image: url(:/image/error_notification_icon.svg);\n"
                                            "}\n"
                                            "\n"
                                            "#confirm_icon {\n"
                                            "    image: url(:/image/question_icon.svg);\n"
                                            "}\n"
                                            "")
        self.background_frame.setObjectName("background_frame")
        self.background_layout = QtWidgets.QVBoxLayout(self.background_frame)
        self.background_layout.setContentsMargins(0, 0, 0, 0)
        self.background_layout.setSpacing(0)
        self.background_layout.setObjectName("background_layout")
        self.pages = QtWidgets.QStackedWidget(self.background_frame)
        self.pages.setObjectName("pages")
        self.add_user_page = QtWidgets.QWidget()
        self.add_user_page.setObjectName("add_user_page")
        self.add_user_layout = QtWidgets.QVBoxLayout(self.add_user_page)
        self.add_user_layout.setContentsMargins(0, 0, 0, 0)
        self.add_user_layout.setSpacing(0)
        self.add_user_layout.setObjectName("add_user_layout")
        self.main_frame = QtWidgets.QFrame(self.add_user_page)
        self.main_frame.setObjectName("main_frame")
        self.main_layout = QtWidgets.QVBoxLayout(self.main_frame)
        self.main_layout.setContentsMargins(30, 35, 30, 30)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.header = QtWidgets.QLabel(self.main_frame)
        self.header.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.header.setObjectName("header")
        self.main_layout.addWidget(self.header)
        self.add_user_text = QtWidgets.QLabel(self.main_frame)
        self.add_user_text.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.add_user_text.setObjectName("add_user_text")
        self.main_layout.addWidget(self.add_user_text)
        self.add_user_role_text = QtWidgets.QLabel(self.main_frame)
        self.add_user_role_text.setObjectName("add_user_role_text")
        self.main_layout.addWidget(self.add_user_role_text)
        self.add_user_radio_butt_frame = QtWidgets.QFrame(self.main_frame)
        self.add_user_radio_butt_frame.setObjectName("add_user_radio_butt_frame")
        self.add_user_radio_butt_layout = QtWidgets.QHBoxLayout(self.add_user_radio_butt_frame)
        self.add_user_radio_butt_layout.setContentsMargins(0, 13, 0, 20)
        self.add_user_radio_butt_layout.setSpacing(34)
        self.add_user_radio_butt_layout.setObjectName("add_user_radio_butt_layout")
        self.main_layout.addWidget(self.add_user_radio_butt_frame, 0, QtCore.Qt.AlignLeft)
        self.name_label = QtWidgets.QLabel(self.main_frame)
        self.name_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.name_label.setObjectName("name_label")
        self.main_layout.addWidget(self.name_label)
        self.name_input = QtWidgets.QLineEdit(self.main_frame)
        self.name_input.setEnabled(True)
        self.name_input.setMinimumSize(QtCore.QSize(540, 48))
        self.name_input.setObjectName("name_input")
        self.main_layout.addWidget(self.name_input)
        self.error_name = QtWidgets.QLabel(self.main_frame)
        self.error_name.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.error_name.setObjectName("error_name")
        self.main_layout.addWidget(self.error_name)
        self.email_label = QtWidgets.QLabel(self.main_frame)
        self.email_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.email_label.setObjectName("email_label")
        self.main_layout.addWidget(self.email_label)
        self.email_input = QtWidgets.QLineEdit(self.main_frame)
        self.email_input.setEnabled(True)
        self.email_input.setMinimumSize(QtCore.QSize(540, 48))
        self.email_input.setObjectName("email_input")
        self.main_layout.addWidget(self.email_input)
        self.error_email = QtWidgets.QLabel(self.main_frame)
        self.error_email.setFocusPolicy(QtCore.Qt.NoFocus)
        self.error_email.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.error_email.setObjectName("error_email")
        self.main_layout.addWidget(self.error_email)
        self.pass_label = QtWidgets.QLabel(self.main_frame)
        self.pass_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.pass_label.setObjectName("pass_label")
        self.main_layout.addWidget(self.pass_label)
        self.pass_input = QtWidgets.QLineEdit(self.main_frame)
        self.pass_input.setEnabled(True)
        self.pass_input.setMinimumSize(QtCore.QSize(540, 48))
        self.pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_input.setObjectName("pass_input")
        self.main_layout.addWidget(self.pass_input)
        self.error_pass = QtWidgets.QLabel(self.main_frame)
        self.error_pass.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.error_pass.setWordWrap(True)
        self.error_pass.setObjectName("error_pass")
        self.main_layout.addWidget(self.error_pass)
        self.pass2_label = QtWidgets.QLabel(self.main_frame)
        self.pass2_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.pass2_label.setObjectName("pass2_label")
        self.main_layout.addWidget(self.pass2_label)
        self.pass2_input = QtWidgets.QLineEdit(self.main_frame)
        self.pass2_input.setEnabled(True)
        self.pass2_input.setMinimumSize(QtCore.QSize(540, 48))
        self.pass2_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass2_input.setObjectName("pass2_input")
        self.main_layout.addWidget(self.pass2_input)
        self.error_pass2 = QtWidgets.QLabel(self.main_frame)
        self.error_pass2.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.error_pass2.setObjectName("error_pass2")
        self.main_layout.addWidget(self.error_pass2)
        self.add_user_bottom_frame = QtWidgets.QFrame(self.main_frame)
        self.add_user_bottom_frame.setObjectName("add_user_bottom_frame")
        self.add_user_bottom_layout = QtWidgets.QHBoxLayout(self.add_user_bottom_frame)
        self.add_user_bottom_layout.setContentsMargins(0, 25, 0, 0)
        self.add_user_bottom_layout.setSpacing(5)
        self.add_user_bottom_layout.setObjectName("add_user_bottom_layout")
        self.add_user_cancel_butt = QtWidgets.QPushButton(self.add_user_bottom_frame)
        self.add_user_cancel_butt.setMinimumSize(QtCore.QSize(131, 47))
        self.add_user_cancel_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_user_cancel_butt.setStyleSheet("")
        self.add_user_cancel_butt.setObjectName("add_user_cancel_butt")
        self.add_user_bottom_layout.addWidget(self.add_user_cancel_butt)
        self.add_user_butt = QtWidgets.QPushButton(self.add_user_bottom_frame)
        self.add_user_butt.setMinimumSize(QtCore.QSize(148, 47))
        self.add_user_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_user_butt.setObjectName("add_user_butt")
        self.add_user_bottom_layout.addWidget(self.add_user_butt)
        self.main_layout.addWidget(self.add_user_bottom_frame, 0, QtCore.Qt.AlignRight)
        self.add_user_layout.addWidget(self.main_frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.pages.addWidget(self.add_user_page)
        self.success_page = QtWidgets.QWidget()
        self.success_page.setObjectName("success_page")
        self.success_layout = QtWidgets.QVBoxLayout(self.success_page)
        self.success_layout.setContentsMargins(0, 0, 0, 0)
        self.success_layout.setSpacing(0)
        self.success_layout.setObjectName("success_layout")
        self.success_frame = QtWidgets.QFrame(self.success_page)
        self.success_frame.setMinimumSize(QtCore.QSize(600, 314))
        self.success_frame.setMaximumSize(QtCore.QSize(600, 314))
        self.success_frame.setObjectName("success_frame")
        self.success_layout_2 = QtWidgets.QVBoxLayout(self.success_frame)
        self.success_layout_2.setContentsMargins(30, 30, 30, 30)
        self.success_layout_2.setSpacing(0)
        self.success_layout_2.setObjectName("success_layout_2")
        self.success_icon = QtWidgets.QLabel(self.success_frame)
        self.success_icon.setMinimumSize(QtCore.QSize(49, 49))
        self.success_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.success_icon.setObjectName("success_icon")
        self.success_layout_2.addWidget(self.success_icon)
        self.success_header = QtWidgets.QLabel(self.success_frame)
        self.success_header.setAlignment(QtCore.Qt.AlignCenter)
        self.success_header.setObjectName("success_header")
        self.success_layout_2.addWidget(self.success_header)
        self.success__text = QtWidgets.QLabel(self.success_frame)
        self.success__text.setMinimumSize(QtCore.QSize(540, 0))
        self.success__text.setAlignment(QtCore.Qt.AlignCenter)
        self.success__text.setWordWrap(True)
        self.success__text.setObjectName("success__text")
        self.success_layout_2.addWidget(self.success__text)
        self.success_butt = QtWidgets.QPushButton(self.success_frame)
        self.success_butt.setMinimumSize(QtCore.QSize(121, 47))
        self.success_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.success_butt.setObjectName("success_butt")
        self.success_layout_2.addWidget(self.success_butt, 0, QtCore.Qt.AlignHCenter)
        self.success_layout.addWidget(self.success_frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.pages.addWidget(self.success_page)
        self.error_page = QtWidgets.QWidget()
        self.error_page.setObjectName("error_page")
        self.error_layout_2 = QtWidgets.QVBoxLayout(self.error_page)
        self.error_layout_2.setContentsMargins(0, 0, 0, 0)
        self.error_layout_2.setSpacing(0)
        self.error_layout_2.setObjectName("error_layout_2")
        self.error_frame = QtWidgets.QFrame(self.error_page)
        self.error_frame.setMinimumSize(QtCore.QSize(600, 314))
        self.error_frame.setMaximumSize(QtCore.QSize(600, 314))
        self.error_frame.setObjectName("error_frame")
        self.error_layout = QtWidgets.QVBoxLayout(self.error_frame)
        self.error_layout.setContentsMargins(30, 30, 30, 30)
        self.error_layout.setSpacing(0)
        self.error_layout.setObjectName("error_layout")
        self.error_icon = QtWidgets.QLabel(self.error_frame)
        self.error_icon.setMinimumSize(QtCore.QSize(49, 49))
        self.error_icon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.error_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.error_icon.setObjectName("error_icon")
        self.error_layout.addWidget(self.error_icon)
        self.error_header = QtWidgets.QLabel(self.error_frame)
        self.error_header.setAlignment(QtCore.Qt.AlignCenter)
        self.error_header.setObjectName("error_header")
        self.error_layout.addWidget(self.error_header)
        self.error_text = QtWidgets.QLabel(self.error_frame)
        self.error_text.setMinimumSize(QtCore.QSize(540, 0))
        self.error_text.setAlignment(QtCore.Qt.AlignCenter)
        self.error_text.setObjectName("error_text")
        self.error_layout.addWidget(self.error_text)
        self.error_bottom_frame = QtWidgets.QFrame(self.error_frame)
        self.error_bottom_frame.setObjectName("error_bottom_frame")
        self.error_bottom_layout = QtWidgets.QHBoxLayout(self.error_bottom_frame)
        self.error_bottom_layout.setContentsMargins(0, 0, 0, 0)
        self.error_bottom_layout.setSpacing(5)
        self.error_bottom_layout.setObjectName("error_bottom_layout")
        self.error_cancel_butt = QtWidgets.QPushButton(self.error_bottom_frame)
        self.error_cancel_butt.setMinimumSize(QtCore.QSize(131, 47))
        self.error_cancel_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.error_cancel_butt.setObjectName("error_cancel_butt")
        self.error_bottom_layout.addWidget(self.error_cancel_butt)
        self.error_butt = QtWidgets.QPushButton(self.error_bottom_frame)
        self.error_butt.setMinimumSize(QtCore.QSize(150, 47))
        self.error_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.error_butt.setObjectName("error_butt")
        self.error_bottom_layout.addWidget(self.error_butt)
        self.error_layout.addWidget(self.error_bottom_frame, 0, QtCore.Qt.AlignHCenter)
        self.error_layout_2.addWidget(self.error_frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.pages.addWidget(self.error_page)
        self.confirm_page = QtWidgets.QWidget()
        self.confirm_page.setObjectName("confirm_page")
        self.confirm_layout = QtWidgets.QVBoxLayout(self.confirm_page)
        self.confirm_layout.setContentsMargins(0, 0, 0, 0)
        self.confirm_layout.setSpacing(0)
        self.confirm_layout.setObjectName("confirm_layout")
        self.confirm_frame = QtWidgets.QFrame(self.confirm_page)
        self.confirm_frame.setMinimumSize(QtCore.QSize(600, 314))
        self.confirm_frame.setMaximumSize(QtCore.QSize(600, 314))
        self.confirm_frame.setObjectName("confirm_frame")
        self.confirm_layout_2 = QtWidgets.QVBoxLayout(self.confirm_frame)
        self.confirm_layout_2.setContentsMargins(30, 30, 30, 30)
        self.confirm_layout_2.setSpacing(0)
        self.confirm_layout_2.setObjectName("confirm_layout_2")
        self.confirm_icon = QtWidgets.QLabel(self.confirm_frame)
        self.confirm_icon.setMinimumSize(QtCore.QSize(49, 49))
        self.confirm_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_icon.setObjectName("confirm_icon")
        self.confirm_layout_2.addWidget(self.confirm_icon)
        self.confirm_header = QtWidgets.QLabel(self.confirm_frame)
        self.confirm_header.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_header.setObjectName("confirm_header")
        self.confirm_layout_2.addWidget(self.confirm_header)
        self.confirm_text = QtWidgets.QLabel(self.confirm_frame)
        self.confirm_text.setMinimumSize(QtCore.QSize(540, 0))
        self.confirm_text.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_text.setWordWrap(True)
        self.confirm_text.setObjectName("confirm_text")
        self.confirm_layout_2.addWidget(self.confirm_text)
        self.confirm_bottom_frame = QtWidgets.QFrame(self.confirm_frame)
        self.confirm_bottom_frame.setObjectName("confirm_bottom_frame")
        self.confirm_bottom_layout = QtWidgets.QHBoxLayout(self.confirm_bottom_frame)
        self.confirm_bottom_layout.setContentsMargins(0, 0, 0, 0)
        self.confirm_bottom_layout.setSpacing(5)
        self.confirm_bottom_layout.setObjectName("confirm_bottom_layout")
        self.confirm_cancel_butt = QtWidgets.QPushButton(self.confirm_bottom_frame)
        self.confirm_cancel_butt.setMinimumSize(QtCore.QSize(101, 47))
        self.confirm_cancel_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_cancel_butt.setObjectName("confirm_cancel_butt")
        self.confirm_bottom_layout.addWidget(self.confirm_cancel_butt)
        self.confirm_accept_butt = QtWidgets.QPushButton(self.confirm_bottom_frame)
        self.confirm_accept_butt.setMinimumSize(QtCore.QSize(181, 47))
        self.confirm_accept_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_accept_butt.setObjectName("confirm_accept_butt")
        self.confirm_bottom_layout.addWidget(self.confirm_accept_butt)
        self.confirm_layout_2.addWidget(self.confirm_bottom_frame, 0, QtCore.Qt.AlignHCenter)
        self.confirm_layout.addWidget(self.confirm_frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.pages.addWidget(self.confirm_page)
        self.asset_page = QtWidgets.QWidget()
        self.asset_page.setObjectName("asset_page")
        self.asset_layout = QtWidgets.QVBoxLayout(self.asset_page)
        self.asset_layout.setContentsMargins(0, 0, 0, 0)
        self.asset_layout.setSpacing(0)
        self.asset_layout.setObjectName("asset_layout")
        self.asset_main_frame = QtWidgets.QFrame(self.asset_page)
        self.asset_main_frame.setObjectName("asset_main_frame")
        self.asset_main_layout = QtWidgets.QVBoxLayout(self.asset_main_frame)
        self.asset_main_layout.setContentsMargins(30, 35, 30, 30)
        self.asset_main_layout.setSpacing(0)
        self.asset_main_layout.setObjectName("asset_main_layout")
        self.asset_header = QtWidgets.QLabel(self.asset_main_frame)
        self.asset_header.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.asset_header.setObjectName("asset_header")
        self.asset_main_layout.addWidget(self.asset_header)
        self.asset_text = QtWidgets.QLabel(self.asset_main_frame)
        self.asset_text.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.asset_text.setObjectName("asset_text")
        self.asset_main_layout.addWidget(self.asset_text)
        self.asset_name_label = QtWidgets.QLabel(self.asset_main_frame)
        self.asset_name_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.asset_name_label.setObjectName("asset_name_label")
        self.asset_main_layout.addWidget(self.asset_name_label)
        self.asset_name_input = QtWidgets.QLineEdit(self.asset_main_frame)
        self.asset_name_input.setEnabled(True)
        self.asset_name_input.setMinimumSize(QtCore.QSize(540, 48))
        self.asset_name_input.setObjectName("asset_name_input")
        self.asset_main_layout.addWidget(self.asset_name_input)
        self.error_asset_name = QtWidgets.QLabel(self.asset_main_frame)
        self.error_asset_name.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.error_asset_name.setObjectName("error_asset_name")
        self.asset_main_layout.addWidget(self.error_asset_name)
        self.asset_type_label = QtWidgets.QLabel(self.asset_main_frame)
        self.asset_type_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.asset_type_label.setObjectName("asset_type_label")
        self.asset_main_layout.addWidget(self.asset_type_label)
        self.asset_type_combobox = QtWidgets.QComboBox(self.asset_main_frame)
        self.asset_type_combobox.setMinimumSize(QtCore.QSize(540, 48))
        self.asset_type_combobox.setMaximumSize(QtCore.QSize(540, 48))
        self.asset_type_combobox.setObjectName("asset_type_combobox")
        self.asset_main_layout.addWidget(self.asset_type_combobox)
        self.asset_add_asset_type = QtWidgets.QPushButton(self.asset_main_frame)
        self.asset_add_asset_type.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.asset_add_asset_type.setIconSize(QtCore.QSize(28, 28))
        self.asset_add_asset_type.setObjectName("asset_add_asset_type")
        self.asset_main_layout.addWidget(self.asset_add_asset_type, 0, QtCore.Qt.AlignRight)
        self.asset_bottom_frame = QtWidgets.QFrame(self.asset_main_frame)
        self.asset_bottom_frame.setObjectName("asset_bottom_frame")
        self.asset_bottom_layout = QtWidgets.QHBoxLayout(self.asset_bottom_frame)
        self.asset_bottom_layout.setContentsMargins(0, 25, 0, 0)
        self.asset_bottom_layout.setSpacing(0)
        self.asset_bottom_layout.setObjectName("asset_bottom_layout")
        self.asset_delete = QtWidgets.QPushButton(self.asset_bottom_frame)
        self.asset_delete.setIconSize(QtCore.QSize(24, 24))
        self.asset_delete.setObjectName("asset_delete")
        self.asset_bottom_layout.addWidget(self.asset_delete, 0, QtCore.Qt.AlignLeft)
        self.asset_button_frame = QtWidgets.QFrame(self.asset_bottom_frame)
        self.asset_button_frame.setObjectName("asset_button_frame")
        self.asset_button_layout = QtWidgets.QHBoxLayout(self.asset_button_frame)
        self.asset_button_layout.setContentsMargins(0, 0, 0, 0)
        self.asset_button_layout.setSpacing(5)
        self.asset_button_layout.setObjectName("asset_button_layout")
        self.cancel_asset_butt = QtWidgets.QPushButton(self.asset_button_frame)
        self.cancel_asset_butt.setMinimumSize(QtCore.QSize(131, 47))
        self.cancel_asset_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_asset_butt.setObjectName("cancel_asset_butt")
        self.asset_button_layout.addWidget(self.cancel_asset_butt)
        self.add_asset_butt = QtWidgets.QPushButton(self.asset_button_frame)
        self.add_asset_butt.setMinimumSize(QtCore.QSize(148, 47))
        self.add_asset_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_asset_butt.setObjectName("add_asset_butt")
        self.asset_button_layout.addWidget(self.add_asset_butt)
        self.asset_bottom_layout.addWidget(self.asset_button_frame, 0, QtCore.Qt.AlignRight)
        self.asset_main_layout.addWidget(self.asset_bottom_frame)
        self.asset_layout.addWidget(self.asset_main_frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.pages.addWidget(self.asset_page)
        self.asset_type_page = QtWidgets.QWidget()
        self.asset_type_page.setObjectName("asset_type_page")
        self.asset_type_layout = QtWidgets.QVBoxLayout(self.asset_type_page)
        self.asset_type_layout.setContentsMargins(0, 0, 0, 0)
        self.asset_type_layout.setSpacing(0)
        self.asset_type_layout.setObjectName("asset_type_layout")
        self.asset_type_main_frame = QtWidgets.QFrame(self.asset_type_page)
        self.asset_type_main_frame.setObjectName("asset_type_main_frame")
        self.asset_type_main_layout = QtWidgets.QVBoxLayout(self.asset_type_main_frame)
        self.asset_type_main_layout.setContentsMargins(30, 35, 30, 30)
        self.asset_type_main_layout.setSpacing(0)
        self.asset_type_main_layout.setObjectName("asset_type_main_layout")
        self.asset_type_header = QtWidgets.QLabel(self.asset_type_main_frame)
        self.asset_type_header.setStyleSheet("")
        self.asset_type_header.setTextFormat(QtCore.Qt.AutoText)
        self.asset_type_header.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.asset_type_header.setIndent(-1)
        self.asset_type_header.setObjectName("asset_type_header")
        self.asset_type_main_layout.addWidget(self.asset_type_header)
        self.asset_type_text = QtWidgets.QLabel(self.asset_type_main_frame)
        self.asset_type_text.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.asset_type_text.setObjectName("asset_type_text")
        self.asset_type_main_layout.addWidget(self.asset_type_text)
        self.asset_type_name_label = QtWidgets.QLabel(self.asset_type_main_frame)
        self.asset_type_name_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.asset_type_name_label.setObjectName("asset_type_name_label")
        self.asset_type_main_layout.addWidget(self.asset_type_name_label)
        self.asset_type_name_input = QtWidgets.QLineEdit(self.asset_type_main_frame)
        self.asset_type_name_input.setMinimumSize(QtCore.QSize(540, 48))
        self.asset_type_name_input.setObjectName("asset_type_name_input")
        self.asset_type_main_layout.addWidget(self.asset_type_name_input)
        self.error_asset_type_name = QtWidgets.QLabel(self.asset_type_main_frame)
        self.error_asset_type_name.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.error_asset_type_name.setObjectName("error_asset_type_name")
        self.asset_type_main_layout.addWidget(self.error_asset_type_name)
        self.asset_type_text_2 = QtWidgets.QLabel(self.asset_type_main_frame)
        self.asset_type_text_2.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.asset_type_text_2.setObjectName("asset_type_text_2")
        self.asset_type_main_layout.addWidget(self.asset_type_text_2)
        self.asset_type_dimension_frame = QtWidgets.QFrame(self.asset_type_main_frame)
        self.asset_type_dimension_frame.setObjectName("asset_type_dimension_frame")
        self.asset_type_dimension_layout = QtWidgets.QHBoxLayout(self.asset_type_dimension_frame)
        self.asset_type_dimension_layout.setContentsMargins(0, 15, 0, 15)
        self.asset_type_dimension_layout.setSpacing(5)
        self.asset_type_dimension_layout.setObjectName("asset_type_dimension_layout")
        self.length_frame = QtWidgets.QFrame(self.asset_type_dimension_frame)
        self.length_frame.setObjectName("length_frame")
        self.length_layout = QtWidgets.QVBoxLayout(self.length_frame)
        self.length_layout.setContentsMargins(0, 0, 0, 0)
        self.length_layout.setSpacing(5)
        self.length_layout.setObjectName("length_layout")
        self.length_label = QtWidgets.QLabel(self.length_frame)
        self.length_label.setObjectName("length_label")
        self.length_layout.addWidget(self.length_label)
        self.length_input = QtWidgets.QLineEdit(self.length_frame)
        self.length_input.setMinimumSize(QtCore.QSize(177, 48))
        self.length_input.setObjectName("length_input")
        self.length_layout.addWidget(self.length_input)
        self.asset_type_dimension_layout.addWidget(self.length_frame)
        self.width_frame = QtWidgets.QFrame(self.asset_type_dimension_frame)
        self.width_frame.setObjectName("width_frame")
        self.width_layout = QtWidgets.QVBoxLayout(self.width_frame)
        self.width_layout.setContentsMargins(0, 0, 0, 0)
        self.width_layout.setSpacing(5)
        self.width_layout.setObjectName("width_layout")
        self.width_label = QtWidgets.QLabel(self.width_frame)
        self.width_label.setObjectName("width_label")
        self.width_layout.addWidget(self.width_label)
        self.width_input = QtWidgets.QLineEdit(self.width_frame)
        self.width_input.setMinimumSize(QtCore.QSize(177, 48))
        self.width_input.setObjectName("width_input")
        self.width_layout.addWidget(self.width_input)
        self.asset_type_dimension_layout.addWidget(self.width_frame)
        self.height_frame = QtWidgets.QFrame(self.asset_type_dimension_frame)
        self.height_frame.setObjectName("height_frame")
        self.height_layout = QtWidgets.QVBoxLayout(self.height_frame)
        self.height_layout.setContentsMargins(0, 0, 0, 0)
        self.height_layout.setSpacing(5)
        self.height_layout.setObjectName("height_layout")
        self.heigth_label = QtWidgets.QLabel(self.height_frame)
        self.heigth_label.setObjectName("heigth_label")
        self.height_layout.addWidget(self.heigth_label)
        self.height_input = QtWidgets.QLineEdit(self.height_frame)
        self.height_input.setMinimumSize(QtCore.QSize(177, 48))
        self.height_input.setObjectName("height_input")
        self.height_layout.addWidget(self.height_input)
        self.asset_type_dimension_layout.addWidget(self.height_frame)
        self.asset_type_main_layout.addWidget(self.asset_type_dimension_frame)
        self.sq_feet_label = QtWidgets.QLabel(self.asset_type_main_frame)
        self.sq_feet_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.sq_feet_label.setObjectName("sq_feet_label")
        self.asset_type_main_layout.addWidget(self.sq_feet_label)
        self.sq_feet_input = QtWidgets.QLineEdit(self.asset_type_main_frame)
        self.sq_feet_input.setMinimumSize(QtCore.QSize(540, 48))
        self.sq_feet_input.setObjectName("sq_feet_input")
        self.asset_type_main_layout.addWidget(self.sq_feet_input)
        self.error_dimension = QtWidgets.QLabel(self.asset_type_main_frame)
        self.error_dimension.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.error_dimension.setObjectName("error_dimension")
        self.asset_type_main_layout.addWidget(self.error_dimension)
        self.asset_type_bottom_frame = QtWidgets.QFrame(self.asset_type_main_frame)
        self.asset_type_bottom_frame.setObjectName("asset_type_bottom_frame")
        self.asset_type_bottom_layout = QtWidgets.QHBoxLayout(self.asset_type_bottom_frame)
        self.asset_type_bottom_layout.setContentsMargins(0, 25, 0, 0)
        self.asset_type_bottom_layout.setSpacing(0)
        self.asset_type_bottom_layout.setObjectName("asset_type_bottom_layout")
        self.asset_type_delete = QtWidgets.QPushButton(self.asset_type_bottom_frame)
        self.asset_type_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.asset_type_delete.setIconSize(QtCore.QSize(24, 24))
        self.asset_type_delete.setObjectName("asset_type_delete")
        self.asset_type_bottom_layout.addWidget(self.asset_type_delete, 0, QtCore.Qt.AlignLeft)
        self.asset_type_button_frame = QtWidgets.QFrame(self.asset_type_bottom_frame)
        self.asset_type_button_frame.setObjectName("asset_type_button_frame")
        self.asset_type_button_layout = QtWidgets.QHBoxLayout(self.asset_type_button_frame)
        self.asset_type_button_layout.setContentsMargins(0, 0, 0, 0)
        self.asset_type_button_layout.setSpacing(5)
        self.asset_type_button_layout.setObjectName("asset_type_button_layout")
        self.cancel_asset_type_butt = QtWidgets.QPushButton(self.asset_type_button_frame)
        self.cancel_asset_type_butt.setMinimumSize(QtCore.QSize(131, 47))
        self.cancel_asset_type_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_asset_type_butt.setObjectName("cancel_asset_type_butt")
        self.asset_type_button_layout.addWidget(self.cancel_asset_type_butt)
        self.add_asset_type_butt = QtWidgets.QPushButton(self.asset_type_button_frame)
        self.add_asset_type_butt.setMinimumSize(QtCore.QSize(116, 47))
        self.add_asset_type_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_asset_type_butt.setObjectName("add_asset_type_butt")
        self.asset_type_button_layout.addWidget(self.add_asset_type_butt)
        self.asset_type_bottom_layout.addWidget(self.asset_type_button_frame, 0, QtCore.Qt.AlignRight)
        self.asset_type_main_layout.addWidget(self.asset_type_bottom_frame)
        self.asset_type_layout.addWidget(self.asset_type_main_frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.pages.addWidget(self.asset_type_page)
        self.invetory_item_page = QtWidgets.QWidget()
        self.invetory_item_page.setObjectName("invetory_item_page")
        self.invetory_item_layout = QtWidgets.QVBoxLayout(self.invetory_item_page)
        self.invetory_item_layout.setContentsMargins(0, 0, 0, 0)
        self.invetory_item_layout.setSpacing(0)
        self.invetory_item_layout.setObjectName("invetory_item_layout")
        self.inventor_item_main_frame = QtWidgets.QFrame(self.invetory_item_page)
        self.inventor_item_main_frame.setObjectName("inventor_item_main_frame")
        self.inventor_item_main_layout = QtWidgets.QVBoxLayout(self.inventor_item_main_frame)
        self.inventor_item_main_layout.setContentsMargins(30, 35, 30, 30)
        self.inventor_item_main_layout.setSpacing(0)
        self.inventor_item_main_layout.setObjectName("inventor_item_main_layout")
        self.inventory_item_header = QtWidgets.QLabel(self.inventor_item_main_frame)
        self.inventory_item_header.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.inventory_item_header.setObjectName("inventory_item_header")
        self.inventor_item_main_layout.addWidget(self.inventory_item_header)
        self.inventory_item_text = QtWidgets.QLabel(self.inventor_item_main_frame)
        self.inventory_item_text.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.inventory_item_text.setObjectName("inventory_item_text")
        self.inventor_item_main_layout.addWidget(self.inventory_item_text)
        self.inventory_item_name_label = QtWidgets.QLabel(self.inventor_item_main_frame)
        self.inventory_item_name_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.inventory_item_name_label.setObjectName("inventory_item_name_label")
        self.inventor_item_main_layout.addWidget(self.inventory_item_name_label)
        self.inventory_item_name_input = QtWidgets.QLineEdit(self.inventor_item_main_frame)
        self.inventory_item_name_input.setMinimumSize(QtCore.QSize(540, 48))
        self.inventory_item_name_input.setObjectName("inventory_item_name_input")
        self.inventor_item_main_layout.addWidget(self.inventory_item_name_input)
        self.error_inventory_item_name = QtWidgets.QLabel(self.inventor_item_main_frame)
        self.error_inventory_item_name.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.error_inventory_item_name.setObjectName("error_inventory_item_name")
        self.inventor_item_main_layout.addWidget(self.error_inventory_item_name)
        self.inventory_item_text_2 = QtWidgets.QLabel(self.inventor_item_main_frame)
        self.inventory_item_text_2.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.inventory_item_text_2.setObjectName("inventory_item_text_2")
        self.inventor_item_main_layout.addWidget(self.inventory_item_text_2)
        self.inventor_item_dimension_frame = QtWidgets.QFrame(self.inventor_item_main_frame)
        self.inventor_item_dimension_frame.setObjectName("inventor_item_dimension_frame")
        self.inventor_item_dimension_layout = QtWidgets.QHBoxLayout(self.inventor_item_dimension_frame)
        self.inventor_item_dimension_layout.setContentsMargins(0, 15, 0, 15)
        self.inventor_item_dimension_layout.setSpacing(5)
        self.inventor_item_dimension_layout.setObjectName("inventor_item_dimension_layout")
        self.inventory_length_frame = QtWidgets.QFrame(self.inventor_item_dimension_frame)
        self.inventory_length_frame.setObjectName("inventory_length_frame")
        self.inventory_length_layout = QtWidgets.QVBoxLayout(self.inventory_length_frame)
        self.inventory_length_layout.setContentsMargins(0, 0, 0, 0)
        self.inventory_length_layout.setSpacing(5)
        self.inventory_length_layout.setObjectName("inventory_length_layout")
        self.inventory_length_label = QtWidgets.QLabel(self.inventory_length_frame)
        self.inventory_length_label.setObjectName("inventory_length_label")
        self.inventory_length_layout.addWidget(self.inventory_length_label)
        self.inventory_length_input = QtWidgets.QLineEdit(self.inventory_length_frame)
        self.inventory_length_input.setMinimumSize(QtCore.QSize(177, 48))
        self.inventory_length_input.setObjectName("inventory_length_input")
        self.inventory_length_layout.addWidget(self.inventory_length_input)
        self.inventor_item_dimension_layout.addWidget(self.inventory_length_frame)
        self.inventory_width_frame = QtWidgets.QFrame(self.inventor_item_dimension_frame)
        self.inventory_width_frame.setObjectName("inventory_width_frame")
        self.inventory_width_layout = QtWidgets.QVBoxLayout(self.inventory_width_frame)
        self.inventory_width_layout.setContentsMargins(0, 0, 0, 0)
        self.inventory_width_layout.setSpacing(5)
        self.inventory_width_layout.setObjectName("inventory_width_layout")
        self.inventory_width_label = QtWidgets.QLabel(self.inventory_width_frame)
        self.inventory_width_label.setObjectName("inventory_width_label")
        self.inventory_width_layout.addWidget(self.inventory_width_label)
        self.inventory_width_input = QtWidgets.QLineEdit(self.inventory_width_frame)
        self.inventory_width_input.setMinimumSize(QtCore.QSize(177, 48))
        self.inventory_width_input.setObjectName("inventory_width_input")
        self.inventory_width_layout.addWidget(self.inventory_width_input)
        self.inventor_item_dimension_layout.addWidget(self.inventory_width_frame)
        self.inventory_height_frame = QtWidgets.QFrame(self.inventor_item_dimension_frame)
        self.inventory_height_frame.setObjectName("inventory_height_frame")
        self.inventory_height_layout = QtWidgets.QVBoxLayout(self.inventory_height_frame)
        self.inventory_height_layout.setContentsMargins(0, 0, 0, 0)
        self.inventory_height_layout.setSpacing(5)
        self.inventory_height_layout.setObjectName("inventory_height_layout")
        self.inventory_heigth_label = QtWidgets.QLabel(self.inventory_height_frame)
        self.inventory_heigth_label.setObjectName("inventory_heigth_label")
        self.inventory_height_layout.addWidget(self.inventory_heigth_label)
        self.inventory_height_input = QtWidgets.QLineEdit(self.inventory_height_frame)
        self.inventory_height_input.setMinimumSize(QtCore.QSize(177, 48))
        self.inventory_height_input.setObjectName("inventory_height_input")
        self.inventory_height_layout.addWidget(self.inventory_height_input)
        self.inventor_item_dimension_layout.addWidget(self.inventory_height_frame)
        self.inventor_item_main_layout.addWidget(self.inventor_item_dimension_frame)
        self.error_inventory_item_dimension = QtWidgets.QLabel(self.inventor_item_main_frame)
        self.error_inventory_item_dimension.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.error_inventory_item_dimension.setObjectName("error_inventory_item_dimension")
        self.inventor_item_main_layout.addWidget(self.error_inventory_item_dimension)
        self.inventor_item_bottom_frame = QtWidgets.QFrame(self.inventor_item_main_frame)
        self.inventor_item_bottom_frame.setObjectName("inventor_item_bottom_frame")
        self.inventor_item_bottom_layout = QtWidgets.QHBoxLayout(self.inventor_item_bottom_frame)
        self.inventor_item_bottom_layout.setContentsMargins(0, 25, 0, 0)
        self.inventor_item_bottom_layout.setSpacing(5)
        self.inventor_item_bottom_layout.setObjectName("inventor_item_bottom_layout")
        self.cancel_inventor_item_butt = QtWidgets.QPushButton(self.inventor_item_bottom_frame)
        self.cancel_inventor_item_butt.setMinimumSize(QtCore.QSize(131, 47))
        self.cancel_inventor_item_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_inventor_item_butt.setObjectName("cancel_inventor_item_butt")
        self.inventor_item_bottom_layout.addWidget(self.cancel_inventor_item_butt)
        self.add_inventor_item_butt = QtWidgets.QPushButton(self.inventor_item_bottom_frame)
        self.add_inventor_item_butt.setMinimumSize(QtCore.QSize(146, 47))
        self.add_inventor_item_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_inventor_item_butt.setObjectName("add_inventor_item_butt")
        self.inventor_item_bottom_layout.addWidget(self.add_inventor_item_butt)
        self.inventor_item_main_layout.addWidget(self.inventor_item_bottom_frame, 0, QtCore.Qt.AlignRight)
        self.invetory_item_layout.addWidget(self.inventor_item_main_frame, 0,
                                            QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.pages.addWidget(self.invetory_item_page)
        self.inventory_preset_page = QtWidgets.QWidget()
        self.inventory_preset_page.setObjectName("inventory_preset_page")
        self.inventory_preset_layout = QtWidgets.QVBoxLayout(self.inventory_preset_page)
        self.inventory_preset_layout.setContentsMargins(0, 0, 0, 0)
        self.inventory_preset_layout.setSpacing(0)
        self.inventory_preset_layout.setObjectName("inventory_preset_layout")
        self.inventory_preset_main_frame = QtWidgets.QFrame(self.inventory_preset_page)
        self.inventory_preset_main_frame.setObjectName("inventory_preset_main_frame")
        self.inventory_preset_main_layout = QtWidgets.QVBoxLayout(self.inventory_preset_main_frame)
        self.inventory_preset_main_layout.setContentsMargins(30, 35, 30, 30)
        self.inventory_preset_main_layout.setSpacing(0)
        self.inventory_preset_main_layout.setObjectName("inventory_preset_main_layout")
        self.inventory_preset_header = QtWidgets.QLabel(self.inventory_preset_main_frame)
        self.inventory_preset_header.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.inventory_preset_header.setObjectName("inventory_preset_header")
        self.inventory_preset_main_layout.addWidget(self.inventory_preset_header)
        self.inventory_preset_text = QtWidgets.QLabel(self.inventory_preset_main_frame)
        self.inventory_preset_text.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.inventory_preset_text.setObjectName("inventory_preset_text")
        self.inventory_preset_main_layout.addWidget(self.inventory_preset_text)
        self.inventory_preset_qty_label = QtWidgets.QLabel(self.inventory_preset_main_frame)
        self.inventory_preset_qty_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.inventory_preset_qty_label.setObjectName("inventory_preset_qty_label")
        self.inventory_preset_main_layout.addWidget(self.inventory_preset_qty_label)
        self.inventory_preset_qty_input = QtWidgets.QLineEdit(self.inventory_preset_main_frame)
        self.inventory_preset_qty_input.setMinimumSize(QtCore.QSize(540, 48))
        self.inventory_preset_qty_input.setObjectName("inventory_preset_qty_input")
        self.inventory_preset_main_layout.addWidget(self.inventory_preset_qty_input)
        self.error_inventory_preset_qty = QtWidgets.QLabel(self.inventory_preset_main_frame)
        self.error_inventory_preset_qty.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.error_inventory_preset_qty.setObjectName("error_inventory_preset_qty")
        self.inventory_preset_main_layout.addWidget(self.error_inventory_preset_qty)
        self.inventory_preset_list_label = QtWidgets.QLabel(self.inventory_preset_main_frame)
        self.inventory_preset_list_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.inventory_preset_list_label.setObjectName("inventory_preset_list_label")
        self.inventory_preset_main_layout.addWidget(self.inventory_preset_list_label)
        self.inventory_preset_combobox = QtWidgets.QComboBox(self.inventory_preset_main_frame)
        self.inventory_preset_combobox.setMinimumSize(QtCore.QSize(540, 48))
        self.inventory_preset_combobox.setMaximumSize(QtCore.QSize(540, 48))
        self.inventory_preset_combobox.setObjectName("inventory_preset_combobox")
        self.inventory_preset_main_layout.addWidget(self.inventory_preset_combobox)
        self.inventory_preset_bottom_frame = QtWidgets.QFrame(self.inventory_preset_main_frame)
        self.inventory_preset_bottom_frame.setObjectName("inventory_preset_bottom_frame")
        self.inventory_preset_bottom_layout = QtWidgets.QHBoxLayout(self.inventory_preset_bottom_frame)
        self.inventory_preset_bottom_layout.setContentsMargins(0, 25, 0, 0)
        self.inventory_preset_bottom_layout.setSpacing(5)
        self.inventory_preset_bottom_layout.setObjectName("inventory_preset_bottom_layout")
        self.cancel_inventory_preset_butt = QtWidgets.QPushButton(self.inventory_preset_bottom_frame)
        self.cancel_inventory_preset_butt.setMinimumSize(QtCore.QSize(131, 47))
        self.cancel_inventory_preset_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_inventory_preset_butt.setObjectName("cancel_inventory_preset_butt")
        self.inventory_preset_bottom_layout.addWidget(self.cancel_inventory_preset_butt)
        self.add_inventory_preset_butt = QtWidgets.QPushButton(self.inventory_preset_bottom_frame)
        self.add_inventory_preset_butt.setMinimumSize(QtCore.QSize(146, 47))
        self.add_inventory_preset_butt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_inventory_preset_butt.setObjectName("add_inventory_preset_butt")
        self.inventory_preset_bottom_layout.addWidget(self.add_inventory_preset_butt)
        self.inventory_preset_main_layout.addWidget(self.inventory_preset_bottom_frame, 0, QtCore.Qt.AlignRight)
        self.inventory_preset_layout.addWidget(self.inventory_preset_main_frame, 0,
                                               QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.pages.addWidget(self.inventory_preset_page)
        self.background_layout.addWidget(self.pages)
        self.dialog_layout.addWidget(self.background_frame)

        self.retranslateUi(dialog)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.header.setText(_translate("dialog", "Add new user"))
        self.add_user_text.setText(_translate("dialog", "Add a new user to your account by filling out a form below."))
        self.add_user_role_text.setText(_translate("dialog", "Assign role to new user:"))
        self.name_label.setText(_translate("dialog", "User Full Name"))
        self.name_input.setPlaceholderText(_translate("dialog", "Enter user full name"))
        self.error_name.setText(_translate("dialog", "Enter user full name"))
        self.email_label.setText(_translate("dialog", "Email"))
        self.email_input.setPlaceholderText(_translate("dialog", "Enter user email"))
        self.error_email.setText(_translate("dialog", "Invalid email address"))
        self.pass_label.setText(_translate("dialog", "Password"))
        self.pass_input.setPlaceholderText(_translate("dialog", "Enter user password"))
        self.error_pass.setText(_translate("dialog",
                                           "Password must be at least 8 characters long contain a number and an uppercase letter"))
        self.pass2_label.setText(_translate("dialog", "Confirm Password"))
        self.pass2_input.setPlaceholderText(_translate("dialog", "Enter user password"))
        self.error_pass2.setText(_translate("dialog", "Passwords do not match"))
        self.add_user_cancel_butt.setText(_translate("dialog", "Cancel"))
        self.add_user_butt.setText(_translate("dialog", "Add User"))
        self.success_header.setText(_translate("dialog", "New user added"))
        self.success__text.setText(_translate("dialog",
                                              "New user account was added seccessfully, a new user will receive an email with the login instructions shortly."))
        self.success_butt.setText(_translate("dialog", "Got It"))
        self.error_header.setText(_translate("dialog", "Looks like something went wrong.."))
        self.error_text.setText(_translate("dialog", "Your request cannot be completed, please try again."))
        self.error_cancel_butt.setText(_translate("dialog", "Cancel"))
        self.error_butt.setText(_translate("dialog", "Try Again"))
        self.confirm_header.setText(_translate("dialog", "Please Confirm"))
        self.confirm_text.setText(_translate("dialog", "Are you sure you want to <user action>?"))
        self.confirm_cancel_butt.setText(_translate("dialog", "No"))
        self.asset_header.setText(_translate("dialog", "Add new asset"))
        self.asset_text.setText(_translate("dialog", "Add a new asset to your equipment by filling out a form below."))
        self.asset_name_label.setText(_translate("dialog", "Asset Name"))
        self.asset_name_input.setPlaceholderText(_translate("dialog", "Enter asset name"))
        self.error_asset_name.setText(_translate("dialog", "Enter asset name"))
        self.asset_type_label.setText(_translate("dialog", "Asset Type"))
        self.asset_add_asset_type.setText(_translate("dialog", " Add Asset Type"))
        self.asset_delete.setText(_translate("dialog", "Delete Asset"))
        self.cancel_asset_butt.setText(_translate("dialog", "Cancel"))
        self.add_asset_butt.setText(_translate("dialog", "Add Asset"))
        self.asset_type_header.setText(_translate("dialog", "Add asset type"))
        self.asset_type_text.setText(
            _translate("dialog", "Add a new asset type to your equipment by filling out a form below."))
        self.asset_type_name_label.setText(_translate("dialog", "Asset type name"))
        self.asset_type_name_input.setPlaceholderText(_translate("dialog", "Enter asset type name"))
        self.error_asset_type_name.setText(_translate("dialog", "Enter asset type name"))
        self.asset_type_text_2.setText(_translate("dialog", "Enter asset dimensions or sq. feet size"))
        self.length_label.setText(_translate("dialog", "Length (ft)"))
        self.length_input.setPlaceholderText(_translate("dialog", "e.g. 24"))
        self.width_label.setText(_translate("dialog", "Width (ft)"))
        self.width_input.setPlaceholderText(_translate("dialog", "e.g. 10"))
        self.heigth_label.setText(_translate("dialog", "Height (ft)"))
        self.height_input.setPlaceholderText(_translate("dialog", "e.g. 10"))
        self.sq_feet_label.setText(_translate("dialog", "Sq. Feet"))
        self.sq_feet_input.setPlaceholderText(_translate("dialog", "e.g. 1000"))
        self.error_dimension.setText(_translate("dialog", "Enter asset dimensions or sq. feet size"))
        self.asset_type_delete.setText(_translate("dialog", "Delete Asset Type"))
        self.cancel_asset_type_butt.setText(_translate("dialog", "Cancel"))
        self.add_asset_type_butt.setText(_translate("dialog", "Save"))
        self.inventory_item_header.setText(_translate("dialog", "Add new item"))
        self.inventory_item_text.setText(_translate("dialog", "Create new item for the inventory list."))
        self.inventory_item_name_label.setText(_translate("dialog", "Item Name"))
        self.inventory_item_name_input.setPlaceholderText(_translate("dialog", "Enter item name"))
        self.error_inventory_item_name.setText(_translate("dialog", "Enter asset type name"))
        self.inventory_item_text_2.setText(_translate("dialog", "Enter item dimensions"))
        self.inventory_length_label.setText(_translate("dialog", "Length (inches)"))
        self.inventory_length_input.setPlaceholderText(_translate("dialog", "e.g. 24"))
        self.inventory_width_label.setText(_translate("dialog", "Width (inches)"))
        self.inventory_width_input.setPlaceholderText(_translate("dialog", "e.g. 10"))
        self.inventory_heigth_label.setText(_translate("dialog", "Height (inches)"))
        self.inventory_height_input.setPlaceholderText(_translate("dialog", "e.g. 10"))
        self.error_inventory_item_dimension.setText(_translate("dialog", "Enter item dimensions"))
        self.cancel_inventor_item_butt.setText(_translate("dialog", "Cancel"))
        self.add_inventor_item_butt.setText(_translate("dialog", "Add Item"))
        self.inventory_preset_header.setText(_translate("dialog", "Add item to the preset"))
        self.inventory_preset_text.setText(_translate("dialog", "Add item to the preset list"))
        self.inventory_preset_qty_label.setText(_translate("dialog", "Item Quantity"))
        self.inventory_preset_qty_input.setPlaceholderText(_translate("dialog", "Enter item quantity"))
        self.error_inventory_preset_qty.setText(_translate("dialog", "Enter item quantity"))
        self.inventory_preset_list_label.setText(_translate("dialog", "List"))
        self.cancel_inventory_preset_butt.setText(_translate("dialog", "Cancel"))
        self.add_inventory_preset_butt.setText(_translate("dialog", "Add Item"))


from resources import resources_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
