# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_equipment_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1383, 887)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#equip_small_header {\n"
                                         "    font-size: 14px;\n"
                                         "    color: #B5B8C7;\n"
                                         "}\n"
                                         "\n"
                                         "#equip_header {\n"
                                         "    font-size: 28px;\n"
                                         "    color: #070808;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Equip_top_frame = QtWidgets.QFrame(self.centralwidget)
        self.Equip_top_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Equip_top_frame.setStyleSheet("")
        self.Equip_top_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Equip_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Equip_top_frame.setObjectName("Equip_top_frame")
        self.Equip_top_layout = QtWidgets.QVBoxLayout(self.Equip_top_frame)
        self.Equip_top_layout.setContentsMargins(30, 25, 15, 0)
        self.Equip_top_layout.setSpacing(0)
        self.Equip_top_layout.setObjectName("Equip_top_layout")
        self.equip_small_header = QtWidgets.QLabel(self.Equip_top_frame)
        self.equip_small_header.setObjectName("equip_small_header")
        self.Equip_top_layout.addWidget(self.equip_small_header)
        self.frame_2 = QtWidgets.QFrame(self.Equip_top_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 50, 15, 30)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.equip_header = QtWidgets.QLabel(self.frame_2)
        self.equip_header.setObjectName("equip_header")
        self.horizontalLayout.addWidget(self.equip_header, 0, QtCore.Qt.AlignLeft)
        self.equip_new_asset_type_butt = QtWidgets.QPushButton(self.frame_2)
        self.equip_new_asset_type_butt.setMinimumSize(QtCore.QSize(165, 36))
        self.equip_new_asset_type_butt.setMaximumSize(QtCore.QSize(165, 36))
        self.equip_new_asset_type_butt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.equip_new_asset_type_butt.setStyleSheet("QPushButton {\n"
                                                     "    border-radius: 5px;\n"
                                                     "    border: 0.5px solid #0915CC;\n"
                                                     "    color: #0915CC;\n"
                                                     "    qproperty-icon: url(:/image/plus_blue_icon.svg);\n"
                                                     "    font-size: 14px;\n"
                                                     "}\n"
                                                     "\n"
                                                     "QPushButton:hover {\n"
                                                     "    border: 0.5px solid rgba(9, 21, 204, 0.8);\n"
                                                     "    color: rgba(9, 21, 204, 0.8);\n"
                                                     "}\n"
                                                     "")
        self.equip_new_asset_type_butt.setIconSize(QtCore.QSize(14, 14))
        self.equip_new_asset_type_butt.setObjectName("equip_new_asset_type_butt")
        self.horizontalLayout.addWidget(self.equip_new_asset_type_butt, 0, QtCore.Qt.AlignRight)
        self.equip_new_asset_butt = QtWidgets.QPushButton(self.frame_2)
        self.equip_new_asset_butt.setMinimumSize(QtCore.QSize(128, 36))
        self.equip_new_asset_butt.setMaximumSize(QtCore.QSize(128, 36))
        self.equip_new_asset_butt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.equip_new_asset_butt.setStyleSheet("QPushButton {\n"
                                                "    background: #0915CC;\n"
                                                "    border-radius: 5px;\n"
                                                "    color: #F2F3F6;\n"
                                                "    qproperty-icon: url(:/image/plus_white_icon.svg);\n"
                                                "    font-size: 14px;\n"
                                                "}\n"
                                                "\n"
                                                "QPushButton:hover {\n"
                                                "    background: rgba(9, 21, 204, 0.8);\n"
                                                "}\n"
                                                "")
        self.equip_new_asset_butt.setIconSize(QtCore.QSize(14, 14))
        self.equip_new_asset_butt.setObjectName("equip_new_asset_butt")
        self.horizontalLayout.addWidget(self.equip_new_asset_butt, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout.setStretch(0, 1)
        self.Equip_top_layout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.Equip_top_frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setStyleSheet("QLabel {\n"
                                   "    background: #0915CC;\n"
                                   "    border-top-left-radius: 3px;\n"
                                   "    border-top-right-radius: 3px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton {\n"
                                   "    background: transparent;\n"
                                   "    font-size: 14px;\n"
                                   "    color: #757C9F;\n"
                                   "    outline: 0;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:hover {\n"
                                   "    color: #0915CC;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton[selected=true] {\n"
                                   "    color: #0915CC;\n"
                                   "}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_calculator_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_calculator_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_calculator_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_calculator_4.setMidLineWidth(0)
        self.frame_calculator_4.setObjectName("frame_calculator_4")
        self.layout_calculator_4 = QtWidgets.QVBoxLayout(self.frame_calculator_4)
        self.layout_calculator_4.setContentsMargins(0, 0, 0, 0)
        self.layout_calculator_4.setSpacing(0)
        self.layout_calculator_4.setObjectName("layout_calculator_4")
        self.button_calculator_4 = QtWidgets.QPushButton(self.frame_calculator_4)
        self.button_calculator_4.setStyleSheet("")
        self.button_calculator_4.setObjectName("button_calculator_4")
        self.layout_calculator_4.addWidget(self.button_calculator_4, 0, QtCore.Qt.AlignTop)
        self.label_calculator_4 = QtWidgets.QLabel(self.frame_calculator_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_calculator_4.sizePolicy().hasHeightForWidth())
        self.label_calculator_4.setSizePolicy(sizePolicy)
        self.label_calculator_4.setMinimumSize(QtCore.QSize(0, 3))
        self.label_calculator_4.setMaximumSize(QtCore.QSize(16777215, 3))
        self.label_calculator_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_calculator_4.setStyleSheet("")
        self.label_calculator_4.setText("")
        self.label_calculator_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_calculator_4.setObjectName("label_calculator_4")
        self.layout_calculator_4.addWidget(self.label_calculator_4)
        self.layout_calculator_4.setStretch(0, 2)
        self.horizontalLayout_2.addWidget(self.frame_calculator_4)
        self.frame_calculator_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_calculator_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_calculator_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_calculator_2.setMidLineWidth(0)
        self.frame_calculator_2.setObjectName("frame_calculator_2")
        self.layout_calculator_2 = QtWidgets.QVBoxLayout(self.frame_calculator_2)
        self.layout_calculator_2.setContentsMargins(0, 0, 0, 0)
        self.layout_calculator_2.setSpacing(0)
        self.layout_calculator_2.setObjectName("layout_calculator_2")
        self.button_calculator_2 = QtWidgets.QPushButton(self.frame_calculator_2)
        self.button_calculator_2.setStyleSheet("")
        self.button_calculator_2.setObjectName("button_calculator_2")
        self.layout_calculator_2.addWidget(self.button_calculator_2, 0, QtCore.Qt.AlignTop)
        self.label_calculator_2 = QtWidgets.QLabel(self.frame_calculator_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_calculator_2.sizePolicy().hasHeightForWidth())
        self.label_calculator_2.setSizePolicy(sizePolicy)
        self.label_calculator_2.setMinimumSize(QtCore.QSize(0, 3))
        self.label_calculator_2.setMaximumSize(QtCore.QSize(16777215, 3))
        self.label_calculator_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_calculator_2.setStyleSheet("")
        self.label_calculator_2.setText("")
        self.label_calculator_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_calculator_2.setObjectName("label_calculator_2")
        self.layout_calculator_2.addWidget(self.label_calculator_2)
        self.layout_calculator_2.setStretch(0, 2)
        self.horizontalLayout_2.addWidget(self.frame_calculator_2)
        self.Equip_top_layout.addWidget(self.frame_3, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.Equip_top_frame, 0, QtCore.Qt.AlignTop)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1383, 687))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(30, 10, 15, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(324, 108))
        self.frame_5.setMaximumSize(QtCore.QSize(324, 108))
        self.frame_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_5.setStyleSheet(".QFrame {\n"
                                   "    border: 0.5px solid rgba(181, 184, 199, 0.5);\n"
                                   "    border-radius: 10px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton {\n"
                                   "    background: transparent;\n"
                                   "    image: url(:/image/equip_edit_default.svg);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:hover {\n"
                                   " image: url(:/image/equip_edit_hover.svg);\n"
                                   "}\n"
                                   "")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setMinimumSize(QtCore.QSize(60, 60))
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setStyleSheet("image: url(:/image/equip_truck.svg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setStyleSheet("border: none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setStyleSheet("color: #070808;\n"
                                   "font-size: 16px;\n"
                                   "margin-bottom: 4px;")
        self.label_2.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setMinimumSize(QtCore.QSize(80, 22))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_3.setStyleSheet("background: #F2F3F6;\n"
                                   "border-radius: 4px;\n"
                                   "font-size: 14px;\n"
                                   "color: #757C9F;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setMinimumSize(QtCore.QSize(12, 12))
        self.label_4.setStyleSheet("image: url(:/image/sq_feet_icon.svg);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setStyleSheet("color: #757C9F;\n"
                                   "font-size: 14px;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout_3.addWidget(self.frame_6, 0, QtCore.Qt.AlignTop)
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.frame_4)
        self.widget.setMinimumSize(QtCore.QSize(324, 108))
        self.widget.setStyleSheet("QWidget {\n"
                                  "    background: #F2F3F6;\n"
                                  "    border-radius: 10px;\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_4, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.equip_small_header.setText(_translate("MainWindow", "Equipment"))
        self.equip_header.setText(_translate("MainWindow", "Equipment"))
        self.equip_new_asset_type_butt.setText(_translate("MainWindow", "New Asset Type  "))
        self.equip_new_asset_butt.setText(_translate("MainWindow", "New Asset  "))
        self.button_calculator_4.setText(_translate("MainWindow", "All Assets ()"))
        self.button_calculator_2.setText(_translate("MainWindow", "Asset Types ()"))
        self.label_2.setText(_translate("MainWindow", "Isuzu"))
        self.label_3.setText(_translate("MainWindow", "Truck 20ft"))
        self.label_5.setText(_translate("MainWindow", "Sq. Feet: 2000 ft2"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))


from resources import resources_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
